[build]
  publish = "public"
  command = "gatsby build"
  NETLIFY_USE_YARN = "true"
[build.environment]
  NODE_VERSION = "18.3.0"
[[headers]]
  for = "/*"
  [headers.values]
    cache-control = '''
	  public,
	  max-age=2592000'''
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Robots-Tag = "index"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"  
    Access-Control-Allow-Methods = '''
      POST, 
      GET,
      PUT,  
      DELETE,
      HEAD
    '''
    Access-Control-Allow-Credentials = "true"
    Vary = "Accept-Encoding"
    Permissions-Policy = '''
      accelerometer=(self),
      ambient-light-sensor=(self),
      autoplay=(self),
      camera=(self),
      encrypted-media=(self),
      fullscreen=(self),
      geolocation=(self),
      gyroscope=(self),
      magnetometer=(self),
      microphone=(self),
      midi=(self),
      payment=(self),
      picture-in-picture=(self),
      speaker=(self),
      usb=(self),
      vibrate=(self),
      vr=(self)
    '''
    Content-Security-Policy = "connect-src 'self' blob: https://github.com https://identity.netlify.com https://api.github.com https://ocsp.digicert.com; form-action 'self'; font-src 'self'; frame-src 'self' https://www.google.com/ https://maps.googleapis.com; img-src 'self' blob: data: https://api.netlify.com; manifest-src 'self'; media-src 'self' blob: ; object-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://api.netlify.com https://netlify.com ; script-src-elem 'self' blob: 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://github.com https://identity.netlify.com; prefetch-src 'self';  worker-src 'self';"
 
[[headers]]
  for = "/static/*"
  [headers.values]
    cache-control = '''
	  public,
	  max-age=31536000'''

